networks:
  canary:
    enable_ipv6: "true"
    driver: bridge
    driver_opts:
      com.docker.network.bridge.gateway_mode_ipv6: routed
    ipam:
      driver: default
      config:
      - subnet: 2001:db8::/64
        gateway: 2001:db8::1
x-common: &common
  restart: unless-stopped
  volumes:
    - ./oc_custom/opencanary.conf:/root/.opencanary.conf
    - ./data/opencanary/log:/var/log/opencanary/
  networks:
    - canary
    # uncomment below if running Samba
    # - /var/log/samba-audit.log:/var/log/samba-audit.log
  image: "opencanary"
    # network_mode: "host"
  ports:
    # Comment/un-comment the port lines below to disable/enable the services you are using
    # FTP
    #- "${CANARY_IPV4}:21:21"
    #- "[${CANARY_IPV6}]:21:21"
    - "21:21"
    # SSH
    - "22:22"
    # Telnet
    - "23:23"
    # TFTP
    # - "69:69"
    # HTTP
    #- "${CANARY_IPV4}:80:80"
    #- "[${CANARY_IPV6}]:80:80"
    - "80:80"
    # NTP
    # - "123:123"
    # SNMP
    # - "161:161"
    # SMB
    - "445:445"
    # MSSQL
    # - "1433:1433"
    # MYSQL
    - "3306:3306"
    # RDP
    # - "3389:3389"
    # VNC
    # - "5000:5000"
    # SIP
    # - "5060:5060"
    # REDIS
    - "6379:6379"
    # TCP Banner
    # - "8001:8001"
    # HTTP Proxy
    # - "8080:8080"
    # Git
    # - "9418:9418"

services:
  latest: # docker-compose up --build -d latest
    <<: *common
    container_name: opencanary_latest
    image: thinkst/opencanary
    build:
      context: ./opencanary
      dockerfile: Dockerfile.latest

